"""empty message

Revision ID: 15fbe0c149d4
Revises: 88e86011a5a8
Create Date: 2022-09-27 22:39:13.224117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fbe0c149d4'
down_revision = '88e86011a5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_user2account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('phone', sa.Integer(), nullable=True, comment='小米登录手机号'),
    sa.Column('password', sa.String(length=125), nullable=True, comment='小米登录密码'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户id'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_user2account')
    # ### end Alembic commands ###
