"""empty message

Revision ID: 2c6977bfdeac
Revises: 303487b78a56
Create Date: 2022-10-08 23:30:35.392112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c6977bfdeac'
down_revision = '303487b78a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_task_log', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ID',
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('file_task_log', 'content',
               existing_type=mysql.TEXT(),
               comment='定时任务日志执行结果内容',
               existing_comment='日志内容',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_task_log', 'content',
               existing_type=mysql.TEXT(),
               comment='日志内容',
               existing_comment='定时任务日志执行结果内容',
               existing_nullable=True)
    op.alter_column('file_task_log', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID',
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
