"""empty message

Revision ID: 6c2c677e5fce
Revises: 7634e028e338
Create Date: 2022-09-22 13:14:10.893041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c2c677e5fce'
down_revision = '7634e028e338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_card',
    sa.Column('card_id', sa.String(length=180), nullable=False, comment='卡密ID'),
    sa.Column('enable', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('expiry_time', sa.DateTime(), nullable=True, comment='失效时间'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户绑定的卡密'),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.drop_table('admin_dept')
    op.drop_table('admin_photo')
    op.add_column('admin_user', sa.Column('email', sa.String(length=20), nullable=True, comment='邮箱'))
    op.add_column('admin_user', sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级用户'))
    op.add_column('admin_user', sa.Column('openid', sa.String(length=255), nullable=True, comment='微信登录openid'))
    op.drop_column('admin_user', 'realname')
    op.drop_column('admin_user', 'dept_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('dept_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='部门id'))
    op.add_column('admin_user', sa.Column('realname', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True, comment='真实名字'))
    op.drop_column('admin_user', 'openid')
    op.drop_column('admin_user', 'is_superuser')
    op.drop_column('admin_user', 'email')
    op.create_table('admin_photo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('href', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('mime', mysql.CHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('size', mysql.CHAR(collation='utf8_unicode_ci', length=30), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('admin_dept',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='部门ID'),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='父级编号'),
    sa.Column('dept_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True, comment='部门名称'),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('leader', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True, comment='负责人'),
    sa.Column('phone', mysql.VARCHAR(collation='utf8_unicode_ci', length=20), nullable=True, comment='联系方式'),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True, comment='邮箱'),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='状态(1开启,0关闭)'),
    sa.Column('remark', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True, comment='备注'),
    sa.Column('address', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True, comment='详细地址'),
    sa.Column('create_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.drop_table('file_card')
    # ### end Alembic commands ###
