"""empty message

Revision ID: 82c3a3142e42
Revises: fd2912bd7c53
Create Date: 2022-09-28 16:55:46.162051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82c3a3142e42'
down_revision = 'fd2912bd7c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_user2account', 'phone',
               existing_type=mysql.VARCHAR(length=125),
               comment='小米登录手机号',
               existing_nullable=True)
    op.create_unique_constraint(None, 'file_user2account', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_user2account', type_='unique')
    op.alter_column('file_user2account', 'phone',
               existing_type=mysql.VARCHAR(length=125),
               comment=None,
               existing_comment='小米登录手机号',
               existing_nullable=True)
    # ### end Alembic commands ###
