"""empty message

Revision ID: 88e86011a5a8
Revises: 58bd52f9172c
Create Date: 2022-09-27 21:58:09.193678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88e86011a5a8'
down_revision = '58bd52f9172c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin_admin_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_admin_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('method', mysql.VARCHAR(collation='utf8_unicode_ci', length=10), nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('desc', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('ip', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('user_agent', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('success', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.drop_table('system_log')
    # ### end Alembic commands ###
