"""empty message

Revision ID: da128430dcec
Revises: 4c36a941732d
Create Date: 2022-09-29 14:55:28.125368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da128430dcec'
down_revision = '4c36a941732d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file_user2push', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_user2push', type_='unique')
    # ### end Alembic commands ###
