"""empty message

Revision ID: e5455c7ef416
Revises: da128430dcec
Create Date: 2022-09-30 08:55:02.613112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5455c7ef416'
down_revision = 'da128430dcec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_card',
    sa.Column('card_id', mysql.VARCHAR(length=180), nullable=False, comment='卡密ID'),
    sa.Column('enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否启用'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('expiry_time', mysql.DATETIME(), nullable=True, comment='失效时间'),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用户绑定的卡密'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], name='file_card_ibfk_1'),
    sa.PrimaryKeyConstraint('card_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
