"""empty message

Revision ID: e9f66fd6ea10
Revises: 2c6977bfdeac
Create Date: 2022-10-08 23:35:04.184206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f66fd6ea10'
down_revision = '2c6977bfdeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_task_log', sa.Column('outcome', sa.Boolean(), nullable=True, comment='是否成功'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_task_log', 'outcome')
    # ### end Alembic commands ###
